services:
  - type: web
    name: vaccine-orders-api
    env: python
    plan: free
    buildCommand: npm install -g bun && bun install && bun run build && pip install -r backend/requirements.txt && cd backend && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    domains:
      - renderphamecom.onrender.com
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,renderphamecom.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://renderphamecom.onrender.com"
      - key: DEBUG
        value: "false"
    disk:
      name: media
      mountPath: /var/data/media
      sizeGB: 1
